apiVersion: v1
kind: Secret
metadata:
  name: db-access
type: Opaque   ##universal type of secret encryption1 one varios of it! 
stringData:
  DB_USER: "appuser"
  DB_PASS: "secretpasswd"    ##must be here!  of the rest no nessesary! 
  DB_NAME: "appdb"
